### ISSUE TITLE
Method Missing

### ISSUE THREAD

**Issue by AadilDAR** [vikesh8860/QuizBook#1]
Firstly Big Thanks For sharing Such A Valuable App.
I have a Request plz view into the issue

sir , please look into the issue ,when questions in database ends before the timer the activity is closed to navigation activity .it should go to result activity.
i think there should be a method when last question is displayed from database it show call the result activity to display score.and this method is missing so it finish the activity Question. plz add the method go to results if we reach the last question in database it show go to Results.class

**Comment by vikesh8860** [comment]
Hey, @AadilDAR  I am slightly busy these days and will be not able to do that. If you have corrected it then please raise a pull request and have something more than don't hesitate to raise pull requests.
