### ISSUE TITLE
How to limit question ?

### ISSUE THREAD

**Issue by anshul0430** [vikesh8860/QuizBook#12]
In Questions Java class.
I want to limit only 10 question .

 if (get.equals("c1")) {

            if (c1 == 0) {
                    for (i = 1; i < 90; i++) {
                        list.add(Integer.valueOf(i));
                    }

                Collections.shuffle(list);
                c1=1;
            }
            Ques = Computer.readQuestion(list.get(j));
            Opta = Computer.readOptionA(list.get(j));
            Optb = Computer.readOptionB(list.get(j));
            Optc = Computer.readOptionC(list.get(j));
            Optd = Computer.readOptionD(list.get(j));
            global = Computer.readAnswer(list.get(j++));

**Comment by vikesh8860** [comment]
Although the app does not limit the number of questions but you can do by creating a global variable and before showing a new question checking if the limit has been reached or not. If yes then simply calling the onfinish() or onstop() as per the needs.

**Comment by anshul0430** [comment]
Lets take an example i want 10 questions.  So i made a global variable n=10
. Then after that how can i use it.
In the Questions class.

**Comment by vikesh8860** [comment]
For. eg if you have selected any category of the question then in that take a counter, initialize it to 0 and after generating a random question check if counter<= n (your global variable). Then when the condition is false then call the stop generating new questions

**Comment by anshul0430** [comment]
if (get.equals("c1")) {

            
            
            if (c1 == 0) {
                    for (i = 1; i < 90; i++) {
                        list.add(Integer.valueOf(i));
                    }

                Collections.shuffle(list);
                c1=1;
            }
            Ques = Computer.readQuestion(list.get(j));
            Opta = Computer.readOptionA(list.get(j));
            Optb = Computer.readOptionB(list.get(j));
            Optc = Computer.readOptionC(list.get(j));
            Optd = Computer.readOptionD(list.get(j));
            global = Computer.readAnswer(list.get(j++));
        }
how to use in this
