### ISSUE TITLE
Using releases

### ISSUE THREAD

**Issue by IzzySoft** [vikesh8860/QuizBook#2]
First, glad to see you're distributing your app as open source! Please allow me a suggestion for easier maintenance:

Instead of using a separate repository just to distribute the `.apk` file: have you ever considered using Github's "release feature" for that? Releases are quite easily created and maintained, and you'd have all in one place. Take a look at [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help for details.

Note that I've integrated your app [with my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/com.kvikesh800gmail.relativlayoutjava), so users can easily install it and receive automatic update informations whenever you release a new APK (if that's not OK with you, just let me know and I'll remove it again).

PS: For a truly free-and-open-source (FOSS) app, consider leaving out those "trackers" (ads) and, if possible, other "proprietary components" (here: Firebase, GMS) :wink:

**Comment by vikesh8860** [comment]
Hey there, I am working on next version of the app and will be soon
updating to the playstore

**Comment by airon90** [comment]
Why don't you create a [release](https://help.github.com/articles/creating-releases/) of 1.0 right now? You would delete the useless repository of hosting APK file :)

**Comment by IzzySoft** [comment]
@vikesh8860 

> Hey there, I am working on next version of the app and will be soon updating to the playstore

I didn't ask for "the playstore" – some of us don't use that "walled garden" :wink: Like @airon90 said, a separate Github repo just for hosting the APK file is a bit awkward, so we're just asking you to provide the file via Github's "releases" system as outlined in my initial post. Indeed that could be done even for the current version: just create the tag for the corresponding commit, attach the last `.apk` to it – and you can drop the other repo. No need to maintain two for the same thing.

**Comment by vikesh8860** [comment]
Thanks for commenting but at the time of upload I don't think know GitHub
release. I will update that soon.

**Comment by IzzySoft** [comment]
@vikesh8860 Just create a tag for a1f627f (your initial commit). The next commit only adds the Readme (which is not part of the APK), and the 3rd commit was already long after the build.

    git tag -s v1.0 a1f627f   # omit the `-s` if you don't want to sign the tag; I see you use verified commits, so I've included that
    git push --tags …

**Comment by vikesh8860** [comment]
Hey, @IzzySoft and @airon90  The release has been created, If you want anything else then do let me know.

**Comment by IzzySoft** [comment]
Thanks, @vikesh8860 – updated the Metadata accordingly, so my updater script will now fetch it from there (whenever you made a new release and attachted an `.apk` to it).

Remaining items now are only those trackers, proprietary elements – and maybe a suitable FOSS license :wink:

**Comment by IzzySoft** [comment]
@vikesh8860 any news on the FOSS license, and removal of trackers etc?
