### ISSUE TITLE
Some answers appear twice

### ISSUE THREAD

**Issue by airon90** [vikesh8860/QuizBook#3]
As the title says,some answers appear twice. You can see it in this screenshot

![screenshot_20180109-003516](https://user-images.githubusercontent.com/139841/34762182-232f6b4e-f5e7-11e7-8962-069a85cceadd.png)

**Comment by vikesh8860** [comment]
Hey there, I m working on the updated version and will be updating soon

**Comment by grumpyoutlaw** [comment]
Great project to help me learn, however I am unable to build a working apk after the deletion of the mainactivity.java file. I will wait for your update before trying it again. Thanks for the hard work

**Comment by WarriorPraise** [comment]
the mainactivity.java is missing

**Comment by mohsinsmsn** [comment]
MainActivity.java is missing, plz update it ASAP

**Comment by airon90** [comment]
@grumpyoutlaw @WarriorPraise @mohsinsmsn 
This bug report is about answers being repeated. Please, open a new bug report about MainActivity.java

**Comment by vikesh8860** [comment]
Hey, @airon90  It happens for just a few questions <10 (at max) and it has happened while creating questions as I have not copy-pasted the questions. So if you have any updated version, I will suggest you raise pull request.
